export const MAIL_REQUEST="MAIL_REQUEST"
export const SEND_MAIL_SUCCESS="ADD_CATEGORY_SUCCESS"
export const SEND_MAIL_FAILED="ADD_CATEGORY_FAILED"
export const CLEAR_SUCCESS='CLEAR_SUCCESS'
export const CLEAR_ERROR='CLEAR_ERROR'